---
title: "Введение в численные методы (Методы вычислений и вычислительная геометрия)"
subtitle: "Описание и программа курса"
author: "Храмов Д.А."
date: "04.02.2019"
output: 
  html_document:
    toc: true
---


Курс знакомит с применением вычислительных методов для решения научных и инженерных задач.


## 1. Модель и моделирование

Что такое модель и моделирование. Зачем нужны модели. Какими бывают модели. 

Процесс принятия решений и место моделирования в нем. Постановка целей. Метод SMART.

Что нового привносит в моделирование компьютер.

**Задачи.** Решение уравнения графическим способом.


## 2. Этапы моделирования. Обыкновенные дифференциальные уравнения

Модель народонаселения Мальтуса. Этапы построения математической модели. Перечень допущений — неотъемлемая составляющая модели. 

Недостатки разностной модели. Переход от разностной модели к обыкновенному дифференциальному уравнению (ОДУ). Аналитическое решение. Поиск аналитического решения в Matlab (модель Мальтуса). Что дает знание аналитического решения.

Исследование при помощи модели. Основные этапы исследования. Недостатки модели Мальтуса и возможности ее развития. Емкость среды. Модель Ферхюльста.

Пример: модель колебаний груза на пружине.

**Задачи.** Найти аналитическое решение дифференциального уравнения.


## 3. Численное решение дифференциальных уравнений

Проблема поиска аналитических решений. Численное решение ОДУ. Метод Эйлера. Локальная и общая ошибки. Причины возникновения ошибок. Точность метода Эйлера. Реализация метода Эйлера на языке Matlab (модель Мальтуса). Проблемы метода Эйлера: малая точность, неустойчивость. Поиски выхода. Модифицированный метод Эйлера.

Решатели ОДУ в Matlab. Приведение ОДУ к каноническому виду.

**Задачи.** Численное решение ДУ методом Эйлера и сравнение результата с аналитическим решением.


## 4. Источники погрешности расчетов

Некоммутативность сложения и другие проблемы. Представление действительных чисел в памяти компьютера. Особенности машинной арифметики.

Приближенные вычисления. Абсолютная и относительная погрешности. Разность двух близких чисел.

Виды погрешностей по их происхождению. Неустранимые погрешности. Расстановка приоритетов.

Пример: логистическое отображение (модель Ферхюльста) и детерминированный хаос.


## 5. Методы Монте-Карло

Статистические испытания. Генератор случайных чисел. Численное интегрирование. Пример: определение числа "пи". Вычисление экстремумов. Моделирование диффузии. Задача о назначениях.

Калибровка модели. Задача об остывании чашки кофе: подбор коэффициента остывания.

**Задачи.** Вычислить интеграл методом Монте-Карло.


## 6. Аппроксимация и прогнозирование

Метод наименьших квадратов (МНК). Задача об остывании чашки кофе возвращается: подбираем коэффициент остывания с помощью МНК. Аппроксимация функций, ее разновидности. Реализация в Matlab (интерполяция: polyfit, семейство interp*; МНК: fit из Curve Fitting Toolbox).

Прогнозирование (регрессия) и аппроксимация: сравнение задач. Проблема переподгонки. Обобщающая способность модели. Кросс-валидация (перекрестная проверка).

**Задачи.** Аппроксимация экспериментальных данных кубическим полиномом.


## 7. Оптимизация: одномерные задачи

Общая постановка задачи оптимизации. Примеры задач оптимизации. Критерий качества, целевая функция, функция потерь. Задачи безусловной оптимизации и оптимизации с ограничениями. Унимодальность функции. 

Аналитическое решение задачи безусловной одномерной оптимизации. Их ограничения. Методы поиска. Интервал неопределенности. Метод перебора. Метод дихотомии. Метод Ньютона. Функция fminbnd.

**Задачи.** Найти минимум функции аналитическим и численным методом. Найти минимум функции, используя разные способы задания функций в Matlab.


## 8. Оптимизация: многомерные задачи

Локальный и глобальный экстремумы. Классификация методов поиска локальных экстремумов (0-го, 1-го и 2-го порядков). 

Метод Ньютона (2-го порядка).

Градиентные методы (1-й порядок). Дробление шага. Метод скорейшего спуска. Примеры. Импульсная добавка. Разновидности градиентного спуска. Проблема оврагов.

Прямые методы поиска 0-го порядка): симплексный метод, метод Нелдера-Мида. Функция fminsearch. Примеры.

Поиск глобального экстремума. Перебор. Мультистарт.

**Задачи.** Найти минимум функции многих переменных (2 задачи).


## 9. Дифференциальные уравнения в частных производных и клеточные автоматы

Диффузия. Концентрация вещества. Вывод уравнения диффузии. Краевые условия. Что делать, если аналитического решения нет. Метод конечных разностей. Разностное уравнение. Программа на Matlab'е. 

Клеточный автомат, моделирующий диффузию. Клеточные автоматы (КА). Правила КА. Правило 30. Игра "Жизнь".


## Литература

1. Бёрд Дж. Инженерная математика: Карманный справочник. — М.: Издательский дом «Додэка-ХХI», 2008.
2. Вержбицкий В. М. Основы численных методов. — М.: Высш. шк., 2002.
3. Мышкис А. Д. Элементы теории математических моделей. 3-е изд., испр. М.: КомКнига, 2007. — 192 с.
4. Шеннон Р. Имитационное моделирование систем — искусство и наука. — М.: Мир, 1978.
5. Kiusalaas J. Numerical Methods in Engineering with MATLAB. 2nd edition. — Cambridge University Press, 2010.
6. Ануфриев И. Е., Смирнов А. Б., Смирнова Е. Н. MATLAB 7. - СПб.: БХВ-Петербург. 2005.
7. Математика для гуманитариев: Учебник / Под общ. ред. К. В. Балдина. — 3-е изд. — М.: Издательско-торговая корпорация «Дашков и К°», 2011.
8. Вычислительная математика. Часть первая / В.С. Асламова,  А.Г. Колмогоров,  Н.Н. Ступакова.  Ангарская  государственная техническая академия. — Ангарск: АГТА, 2003г.
9. Вычислительная математика. Часть вторая / В.С. Асламова, А.Г. Колмогоров, Н.Н. Сумарокова. Ангарская государственная техническая академия. — Ангарск: АГТА, 2005г.
10. Математические  расчеты  в  MATLAB:  методические  указания  /  сост.: Н.Ф. Антипенко, Т.А. Санькова. — Омск: СибАДИ, 2010.
11. Пантелеев А. В., Летова Т. А. Методы оптимизации в примерах и задачах: Учебное пособие. — 4-е изд., испр. — СПб.: Издательство «Лань», 2015.
12. Плохотников К.Э. Метод и искусство математического моделирования. — М. : ФЛИНТА, 2012.
13. Поршнев С. В. Вычислительная математика. Курс лекций. — СПб.: БХВ-Петербург, 2004.
14. Поршнев С. В. Компьютерное моделирование физических процессов в пакете MATLAB: Учебное пособие. 2-е изд., испр. — СПб.: Издательство «Лань», 2011.
